FROM heroku/heroku:24-build

USER root

# Install PHP and Node.js 20 dependencies
RUN mkdir -p /var/lib/apt/lists/partial && chmod -R 755 /var/lib/apt/lists && \
    apt-get update && apt-get install -y curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y \
    php \
    php-cli \
    php-fpm \
    php-mysql \
    php-sqlite3 \
    php-mbstring \
    php-xml \
    php-curl \
    php-gd \
    php-zip \
    php-bcmath \
    composer \
    nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY . .

# Set permissions
RUN chmod +x boot.sh
RUN mkdir -p /app/database /app/storage
RUN chmod -R 777 /app/database /app/storage

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader --no-interaction

# Clear any stale cached config/routes/views copied from the host before rebuilding
RUN php artisan config:clear && php artisan route:clear && php artisan view:clear

# Install JS dependencies and build frontend assets (Bootstrap, CoreUI, Bootstrap Icons, custom CSS/JS).
# This generates public/build/ (including manifest.json) which Laravel's @vite() directive relies on.
# public/build is gitignored for git purposes only - it is NOT excluded from the Docker build context
# (no .dockerignore entry) and is generated fresh in this image layer, so it persists in the container.
RUN npm install && npm run build

# Verify the Vite manifest was generated - fail the build loudly if assets are missing
RUN test -f /app/public/build/manifest.json || (echo "ERROR: public/build/manifest.json was not generated by npm run build" && exit 1)

# Cache routes and views for production. Config caching is intentionally skipped -
# it interferes with Laravel's runtime resolution of the Vite manifest, which breaks
# @vite() asset loading (CSS/JS fail to render on pages).
RUN php artisan route:cache
RUN php artisan view:cache

EXPOSE 8000

CMD ["sh", "-c", "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"]
